"""appended secondary table activityTree

Revision ID: 4e6f1a23fa58
Revises: a96ceab901d2
Create Date: 2026-02-28 17:59:07.074985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e6f1a23fa58'
down_revision: Union[str, Sequence[str], None] = 'a96ceab901d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activitytree',
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('child_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activitytree_id'), 'activitytree', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activitytree_id'), table_name='activitytree')
    op.drop_table('activitytree')
    # ### end Alembic commands ###
